node {
  stage('SCM') {
    git 'https://github.com/solmedo13/holamundo'
  }
  stage('SonarQube analysis') {
  
    withSonarQubeEnv('SonarServer') {
      // requires SonarQube Scanner for Maven 3.2+
      sh '/var/jenkins_home/apache-maven-3.5.4/bin/mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar' +
                '-f all/pom.xml ' +
          '-Dsonar.projectKey=org.tfg:all:master ' +
          '-Dsonar.login=$SONAR_UN ' +
          '-Dsonar.password=$SONAR_PW ' +
          '-Dsonar.language=java ' +
          '-Dsonar.sources=. ' +
          '-Dsonar.tests=. ' +
          '-Dsonar.test.inclusions=**/*Test*/** ' +
          '-Dsonar.exclusions=**/*Test*/**'
    }
  }
  stage ('test'){
  		sh '/var/jenkins_home/apache-maven-3.5.4/bin/mvn test'
  }
}