node {
  stage('SCM') {
    git 'https://github.com/solmedo13/holamundo'
  }
  stage('SonarQube analysis') {
  environment {
	        PATH=/var/jenkins_home/apache-maven-3.5.4:$PATH
	    }
    withSonarQubeEnv('SonarServer') {
      // requires SonarQube Scanner for Maven 3.2+
      sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
    }
  }
}