node {
  stage('SCM') {
    git 'https://github.com/solmedo13/holamundo'
  }
  stage('SonarQube analysis') {
  
    withSonarQubeEnv('SonarServer') {
      // requires SonarQube Scanner for Maven 3.2+
      sh '/var/jenkins_home/apache-maven-3.5.4/bin/mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
    }
  }
  stage ('test'){
  		sh 'mvn test'
  }
}